language: python
python:
  - "3.7.1"

# command to install dependencies
install:
  - pip install numpy
  - pip install scipy
  - pip install numdifftools
  - pip install chaospy

# Branches to avoid building
branches:
  except:
    - codebreaking
    # - omdao_workshop

# command to run tests
script:
  - python ./test/test_stochastic_collocation.py
  - python ./test/test_hadamard_quadratic.py
  - python ./test/test_dimension_reduction.py
  - python ./test/test_arnoldi_sampling.py

notifications:
  email:
    - pandak@rpi.edu
