language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install numpy
  - pip install scipy
  - pip install numdifftools
  - pip install chaospy

# command to run tests
script:
  - python ./test/test_stochastic_collocation.py
  - python ./test/test_hadamard_quadratic.py
  - python ./test/test_dimension_reduction.py
