from exponential_function import ExponentialFunction
from hadamard_quadratic import HadamardQuadratic
from paraboloid import Paraboloid2D, Paraboloid3D, Paraboloid5D
from random_quadratic import RandomQuadratic
from simple_classes import ConstantFunction, LinearFunction
